### PR TITLE
Task 6 (SQS & SNS, Async Microservices Communication)

### PR DESCRIPTION
**Pull request by avorakh**
1. Task: [Task 6 (SQS & SNS, Async Microservices Communication) link](https://github.com/rolling-scopes-school/aws/blob/main/aws-developer/06_async_microservices_communication/task.md)
2. Screenshot:
- Emails (avorakh.my.shop@yopmail.com) related to sending an event to the SNS topic once it creates products.
image
- Emails related to  the Filter Policy for SNS createProductTopic in AWS CDK Stack and  an additional email subscriptions to distribute messages to different emails depending on the filter for any product attribute
    - avorakh.my.shop.count@yopmail.com - price is greater than 10.
    
image

    - avorakh.my.shop.count@yopmail.com - count is less than 5.
    
image

3. Deploy: - Deployment Links:
 - [Frontend application - CloudFront URL](https://d1042f2eyyzqju.cloudfront.net)
 
4. Done 05.07.2024 / deadline 08.07.2024

5. Score: 100 / 100

Evaluation criteria (70 points for covering all criteria)

---

Reviewers should verify the lambda functions, SQS and SNS topic and subscription in PR.

- [x] AWS CDK Stack contains configuration for `catalogBatchProcess` function
    - [CDK Stack - MyShopBackendJavaStack.java (145-167 lines)](https://github.com/avorakh/java-aws-shop-api/blob/task-06/cdk-backend-java/src/main/java/dev/avorakh/shop/cdk/MyShopBackendJavaStack.java)
- [x] AWS CDK Stack contains policies to allow lambda `catalogBatchProcess` function to interact with SNS and SQS
    - [CDK Stack - MyShopBackendJavaStack.java (163-169 lines)](https://github.com/avorakh/java-aws-shop-api/blob/task-06/cdk-backend-java/src/main/java/dev/avorakh/shop/cdk/MyShopBackendJavaStack.java)
- [x] AWS CDK Stack contains configuration for SQS `catalogItemsQueue`
    - [CDK Stack - MyShopBackendJavaStack.java (109, 172-187 lines)](https://github.com/avorakh/java-aws-shop-api/blob/task-06/cdk-backend-java/src/main/java/dev/avorakh/shop/cdk/MyShopBackendJavaStack.java)
- [x] AWS CDK Stack contains configuration for SNS Topic `createProductTopic` and email subscription
    - [CDK Stack - MyShopBackendJavaStack.java (118-142 lines)](https://github.com/avorakh/java-aws-shop-api/blob/task-06/cdk-backend-java/src/main/java/dev/avorakh/shop/cdk/MyShopBackendJavaStack.java)

## Additional (optional) tasks

---

- [x] **+15** **(All languages)** - `catalogBatchProcess` lambda is covered by **unit** tests
    - [The `catalogBatchProcess` lambda function unit tests with Localstack and TestContainers - LambdaHandlerTest.groovy ](https://github.com/avorakh/java-aws-shop-api/blob/task-06/product-service/catalog-batch-process-function/src/test/groovy/dev/avorakh/shop/function/LambdaHandlerTest.groovy)
- [x] **+15** **(All languages)** - set a Filter Policy for SNS `createProductTopic` in AWS CDK Stack and create an additional email subscription to distribute messages to different emails depending on the filter for any product attribute
    - [CDK Stack - MyShopBackendJavaStack.java (128-142 lines)](https://github.com/avorakh/java-aws-shop-api/blob/task-06/cdk-backend-java/src/main/java/dev/avorakh/shop/cdk/MyShopBackendJavaStack.java)

### CODE REVIEW

**Comment by furiousme** [comment]
@avorakh 
Hello! I have just tried to upload two files with products to your app, but something went wrong, they didn't appear in the list. Could you please check the logs to figure out what happened?

**Comment by avorakh** [comment]
> @avorakh Hello! I have just tried to upload two files with products to your app, but something went wrong, they didn't appear in the list. Could you please check the logs to figure out what happened?

@furiousme ,

we use the different CSV file format. 
image

my format is https://github.com/avorakh/java-aws-shop-api/blob/main/import-service/products.csv:
```
id,title,description,price,count
```

your format is :
```
title,description,price,count
```
image


Also, we use the different type for price. My type is INT, your format is FLOAT/DOUBLE.

FYI, 
There are no criteria to verify the change working.
Could you please verify the source code with results in the screen shot?

**Comment by furiousme** [comment]
@avorakh Of course I'm aware of the requirements, and I'm not going to cut off the points. The reason why I'm asking for logs is just for both of us to make sure the application works correctly, as to me this is more important than points. Isn't it?

**Comment by avorakh** [comment]
> @avorakh Of course I'm aware of the requirements, and I'm not going to cut off the points. The reason why I'm asking for logs is just for both of us to make sure the application works correctly, as to me this is more important than points. Isn't it?

@furiousme ,
Unit tests cover the general work of the components (The project is integrated with CI based on GitHub actions) Also, the provided screenshots show E2E results (received emails based on SNS topic subscriptions).

Could you please follow the review criteria and avoid any personal preference?

**Pull request merged**
